### ISSUE TITLE
Developer experience audit from @mntnr

### ISSUE THREAD

**Issue by RichardLitt** [probot/stale#127]
:wave: Hey there! This is the developer experience audit from @mntnr for this repository. I've added in my thoughts below, in the form of a checklist. Looking forward to seeing what you think; let's see if we can resolve all of the open issues and make this repository shine ✨ 💖 ✨

# Repository Review: [probot/stale](https://github.com/probot/stale)

> automatically close stale Issues and Pull Requests

_For notes on anything crossed out, look below. Note: I use `[~]` to mean that I have proposed a fix in a PR. I know it doesn't render properly in Markdown, but it works pretty well otherwise for that purpose. If I think that something is fine, even if it isn't valid according to this checklist, I've checked it off and included a note._

### Reviewing the Repository Docs

- [x] Is there a README?
  ~~- [] Does it follow [standard-readme](https://github.com/RichardLitt/standard-readme)? _More or less._~~
  - [x] Is it spellchecked?
- [x] Is there a Code of Conduct, such as the [Contributor Covenant](https://github.com/simonv3/covenant-generator)?
  - [x] Is it mentioned in the Contribute section of the README? (Note: this isn't needed if you mention it in your CONTRIBUTE.md and it is in this repository.)
  - [x] Does it reference an email address for violations?
- [x] Is there a `LICENSE` file?
  - [x] Is this matched in the `package.json`?
  - [x] Is the year correct?
- [x] Is there a `.github` or `docs` folder?
  ~~- [ ] Is there an `ISSUE_TEMPLATE.md`?~~
  ~~- [ ] Is there a `PULL_REQUEST_TEMPLATE.md`?~~
- [x] Is there a `CONTRIBUTING.md` file?
  - [x] Does it mention how to make a PR?
  - [x] Does it mention what sort of issues you'd like?
  - [x] Does it mention a `good first issue` label as a starting point?
  - [ ] Does it mention triaging and bug reports as good starting points?
  - [x] Does it point to a community chat program, like Slack or Gitter?
  - [x] Does it encourage conversations in issues before opening huge PRs?
  - [x] Does it specify where to ask questions on process?
  - [ ] Does it explain labels used in the issues?
- [x] Is there a `CHANGELOG`? _Releases_
  - [x] If there isn't, are notes included in the project's releases?
- [x] Does this pass [`alex`](https://github.com/wooorm/alex) adequately? Run `alex *.md`.
- [x] Does the repository name itself pass on http://wordsafety.com?

### Process
- [x] Can I install easily?
- [x] Can I use this easily?

### Issues and Pull Requests
- [x] Are there an acceptable amount of pull requests?
- [x] Are there an acceptable amount of issues?
- [x] Are an acceptable amount of issues less than six months old? _Ironically._
- [ ] Are there useful issue labels? _There could definitely be some more triaging._
- [ ] Are the labels being used? _No._
- [ ] Is there a `good for beginners` or `good first issue` label? _Not that I can see at the moment._
- [ ] Is there a `waiting on contributor` label? _No._

### Bots

_Note: Neither of these are necessary, but they can help with some things. Check out https://probot.github.io/ for some tools._

- [x] Are there bots enabled? _Stale._
- [x] Are the bots listed in the Contribute or Readme files so that users can expect to interact with them?

### Metadata
- [x] Is there a description on GitHub?
  - [ ] Does the description match the README?
- [x] Are the topics useful?
- [x] Is there a website?
  - [x] Does the website match the project?

### Package Metadata

Note: These should apply to `package.json` (JavaScript), `*.cabal` (Haskell), and `metadata.yml` (Perl), among others.

- [x] Does the description match the GitHub description?
- [x] Is there a `bugs` field?
- [x] Is there a `homepage` field?
- [x] Are there appropriate `keywords`?
  - [x] Do these match the topics on GitHub?
- [ ] Run [`depcheck`](https://www.npmjs.com/package/depcheck); do the deps make sense? _See below_
  - Unused dependencies
    * standard
  - Unused devDependencies
    * jest
    * smee-client

### TODO

This repository is also doing fine. I've added a PR that should solve most of the issues I found.

#### Generic
- [x] Change the description to "A GitHub App built with Probot that closes abandoned Issues and Pull Requests after a period of inactivity." to match the README. This one is more informative, too!
- [ ] I would add a maintainers section, to make it clear who is on the maintainers team. This helps set expectations and clarifies for the users who they can talk to.
- [~] Add a link to your Slack or Gitter! You want to engage with users there.
- [ ] Consider adding `ISSUE_TEMPLATE.md` and `PULL_REQUEST_TEMPLATE.md` files to your repository. It looks like you have your PRs well under control, but these may help you in the future. At the least, ask them to run the tests, first, and to read the Usage guides.
- [ ] This audit does _not_ cover license dependency. For that, I suggest using either [licensee](https://github.com/jslicense/licensee.js) or an external tool like [Fossa](https://fossa.io/). Let me know if you want more help here.

#### Issues
- [ ] Create some `good first issues`! You don't have any right now.
- [ ] Add 'discussion' labels to longstanding issues.
- [ ] Considering adding `available` labels as well as `good first issue`. These can be used to signal that you're looking for community involvement for issues. They can also be configured to display on http://up-for-grabs.net. This will help more people interact with your code, and lead to small, iterative work done by others. It may take some time to set up initially - properly scoping issues for newcomers takes some time - but the payback should be worth it.
- [ ] I label pull requests where I am waiting on the Contributor to respond `waiting on contributor`. This helps alleviate pressure on you to close them.

## Contribute back?

This checklist is open source! If you have suggestions or think it could be better, contribute back on [mntnr/audit-templates](https://github.com/mntnr/audit-templates).

Thank you!

**Comment by RichardLitt** [comment]
I've gone through and checked off the changes that should have been fixed in the PR. Anything else you want to pull out from this issue and open as separate issues or fix before we close this? :) @bkeepers
